# Generated by Django 3.2.7 on 2022-02-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Новая тема', max_length=255),
        ),
    ]
