# Generated by Django 3.2.7 on 2022-03-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
